Name :Rutuja Dayanand Birajdar

Roll no: 23092008

IMCA 1st

# Q3. Singular Value Decomposition (SVD):


Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print 
matrices U, Σ, and 𝑉
்
. Verify that A equals the product of U, Σ, and 𝑉
்
. Additionally, find the rank 2 
and rank 3 approximations of matrix A.

In [11]:
#Perform SIngularvakue decomposition (SVD)
import numpy as np


np.random.seed(2)


A = np.random.randint(0, 10, size=(5, 5))
print("Matrix A:")
print(A)

Matrix A:
[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]
 [3 5 8 4 6]]


In [12]:
#Perform SIngularvakue decomposition (SVD)
U, S, Vt = np.linalg.svd(A)
print("\nMatrix U:")
print(U)
print("\nMatrix Sigma:")
print(np.diag(S))
print("\nMatrix Vt:")
print(Vt)


Matrix U:
[[-5.81305618e-01 -5.03654582e-01 -3.31511571e-01  5.14809089e-01
   1.82995956e-01]
 [-3.20241693e-01 -4.95054048e-01  7.07063522e-01 -3.90419782e-01
  -5.63638852e-04]
 [-4.53779839e-01  1.37875020e-01 -2.47842758e-01 -2.50300244e-01
  -8.06844528e-01]
 [-3.65208499e-01  5.86353965e-01  5.21576739e-01  5.00670256e-01
  -9.93882503e-03]
 [-4.69292709e-01  3.72065933e-01 -2.38102765e-01 -5.18867110e-01
   5.61618456e-01]]

Matrix Sigma:
[[25.27873539  0.          0.          0.          0.        ]
 [ 0.          6.51755471  0.          0.          0.        ]
 [ 0.          0.          6.05540789  0.          0.        ]
 [ 0.          0.          0.          2.17898879  0.        ]
 [ 0.          0.          0.          0.          0.3017626 ]]

Matrix Vt:
[[-0.45793305 -0.43522417 -0.52594939 -0.32412939 -0.46818226]
 [-0.53417292 -0.10902526  0.69491535  0.29726381 -0.36262882]
 [ 0.44224597 -0.34728675 -0.20984386  0.71106945 -0.36627341]
 [ 0.38110015  0.4560864   0.13

In [13]:
#TO show that A equals to  U, Sigma & V
A_reconstructed = np.dot(U, np.dot(np.diag(S), Vt))
print("\nReconstructed Matrix A:")
print(A_reconstructed)


Reconstructed Matrix A:
[[8. 8. 6. 2. 8.]
 [7. 2. 1. 5. 4.]
 [4. 5. 7. 3. 6.]
 [4. 3. 7. 6. 1.]
 [3. 5. 8. 4. 6.]]


In [14]:
# Rank 2 approximation
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(S[:2]), Vt[:2, :]))
print("\nRank 2 Approximation of Matrix A:")
print(rank_2_approximation)



Rank 2 Approximation of Matrix A:
[[8.48264945 6.75336182 5.44752663 3.7871776  8.07014827]
 [5.43063897 3.87504695 2.01554728 1.66479213 4.96011527]
 [4.77292897 4.89447696 6.65761165 3.98520552 5.04464843]
 [2.18624993 3.60134315 7.51125386 4.12838706 2.93644271]
 [4.1371695  4.89873732 7.92454596 4.56604073 4.67474485]]


In [15]:
# Rank 3 approximation
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(S[:3]), Vt[:3, :]))
print("\nRank 3 Approximation of Matrix A:")
print(rank_3_approximation)


Rank 3 Approximation of Matrix A:
[[7.59486819 7.45051837 5.86877512 2.35974991 8.80541935]
 [7.32414074 2.38811858 1.11708862 4.70927725 3.39189442]
 [4.10921109 5.41568109 6.97254301 2.91804032 5.59434753]
 [3.58302185 2.5044866  6.84849143 6.3742003  1.77961947]
 [3.49953512 5.39945861 8.2271008  3.54081413 5.20284128]]
